# @name findMany
GET {{HOST}}/products

###

# @name findById
GET {{HOST}}/products/1

###

# @name create
POST {{HOST}}/products
Content-Type: application/json

{
  "name": "Nusita",
  "description": "pudin de chocolate y vainilla",
  "price": 600,
  "stock": 40,
  "image": "https://ecommerce.com/nusita.png",
  "brandId": 1
}

###

# @name update
PUT {{HOST}}/products/1
Content-Type: application/json

{
  "stock": 88
}

###

# @name remove
DELETE {{HOST}}/products/1
