# Variables
@acces_token = {{login.response.body.access_token}}
@authorization = Authorization: Bearer {{acces_token}}

# @name login
POST {{HOST}}/auth/login
Content-Type: application/json

{
  "email": "bob@gmail.com",
  "password": "1234563"
}

###

# @name findManyByCustomer
GET {{HOST}}/profile/my-orders
{{authorization}}
